### ISSUE TITLE
'module' object has no attribute '_getframe'

### ISSUE THREAD

**Issue by JustinShultz** [architecture-building-systems/idf-plotter#1]
Hi Daren,

I came across your architecture building systems github and found the idf-plotter to be particularly interesting. I installed Ply and gave it a run. I have the script and .idf files in the same folder but each time I run I get the error: 

```
C:\Users\justin.shultz\Documents\05Research>python findreferences.py -i "1ZoneUncontrolled.idf" > "names.txt"
Traceback (most recent call last):
  File "findreferences.py", line 50, in <module>
  File "C:\Users\justin.shultz\Documents\05Research\parseidf.py", line 99, in parse
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\ply\lex.py", line 893, in lex
 File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\ply\lex.py", line 450, in get_caller_module_dict
AttributeError: 'module' object has no attribute '_getframe'
```

Looking at the trace back the findreference.py is having problems with the parse.py. Within parse.py line 99 is: 
`lexer = lex.lex(debug=False)`
within the parse function.

Any ideas?

**Comment by daren-thomas** [comment]
Hi Justin,

Huh... that's weird... would you mind sending me the file
"1ZoneUncontrolled.idf" - or is that a standard E+ file? I'll take a look
and report back...

Oh... wait... It looks like you're running IronPython! I never really
tested the idf-plotter with other python implementations (only CPython).
Could you give it a spin on CPython? It could be that ply doesn't really
work on IronPython - waitaminute...

Look here:
http://stackoverflow.com/questions/6997832/ironpython-sys-getframe-not-found

If you really are on IronPython, try adding the option -X:FullFrames to
your python invocation. Does that help?

Best,
Daren

**Comment by JustinShultz** [comment]
Hi Daren, 

You were spot on, that fixed it! Apologizes for not catching that myself, I normally use CPython too but my work machine has IronPython. 

Excellent little tool, I appreciate your work. 

Thank you,
Justin

**Comment by daren-thomas** [comment]
Justin,

you just made my day! I would never have guessed someone could be
interested in this little tool (that I personally haven't looked at in
ages!)

Have a nice weekend!
Daren
